name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'                                 # Dependency caching :contentReference[oaicite:10]{index=10}
        cache-dependency-path: '**/package-lock.json'
        check-latest: true                           # Ensure latest minor/patch :contentReference[oaicite:11]{index=11}

    - name: Configure npm
      run: |
        echo "engine-strict=false" >> ~/.npmrc      # Ignore engine warnings :contentReference[oaicite:12]{index=12}

    - name: Install dependencies
      run: npm ci                                  # Use ci for reproducible installs

    - name: Start the bot
      env:
        PORT: 8080
      run: npm start
